Parameters:
  BucketName:
    Type: String
    Description: The bucket's name which will contain all the project's files.
  AmiId:
    Type: String
    Description: The AMI ID on which the compliance checks will run on (must be a RHEL-based AMI).
  GitHubRepository:
    Type: String
    Description: |
      The owner and name of the repository where source changes are to be detected.
      Example: some-user/my-repo
  BranchName:
    Type: String
  
Resources:
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudformation/lambda.yaml
      Parameters:
        BucketName: !Ref BucketName

  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudformation/codebuild.yaml
      Parameters:
        BucketName: !Ref BucketName

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudformation/codepipeline.yaml
      Parameters:
        BucketName: !Ref BucketName
        CodeBuildProjectArn:
          Fn::GetAtt: [CodeBuildStack, Outputs.CodeBuildProjectArn]
        CodeBuildProjectName:
          Fn::GetAtt: [CodeBuildStack, Outputs.CodeBuildProjectName]
        LambdaArn:
          Fn::GetAtt: [LambdaStack, Outputs.LambdaArn]
        LambdaName:
          Fn::GetAtt: [LambdaStack, Outputs.LambdaName]
        GitHubRepository: !Ref GitHubRepository
        BranchName: !Ref BranchName
