Parameters:
  BucketName:
    Type: String
    Description: The bucket's name which will contain all the project's files.
  AmiId:
    Type: String
    Description: The AMI ID on which the compliance checks will run on (must be a RHEL-based AMI).
  GitHubRepository:
    Type: String
    Description: |
      The owner and name of the repository where source changes are to be detected.
      Example: some-user/my-repo
  BranchName:
    Type: String
  
Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource:
                  Fn::Sub:
                    - arn:aws:s3:::${Bucket}/*
                    - Bucket: !Ref BucketName

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: ami-factory
      Roles:
        - !Ref EC2Role

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudformation/lambda.yaml
      Parameters:
        BucketName: !Ref BucketName

  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudformation/codebuild.yaml
      Parameters:
        BucketName: !Ref BucketName

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudformation/codepipeline.yaml
      Parameters:
        BucketName: !Ref BucketName
        CodeBuildProjectArn:
          Fn::GetAtt: [CodeBuildStack, Outputs.CodeBuildProjectArn]
        CodeBuildProjectName:
          Fn::GetAtt: [CodeBuildStack, Outputs.CodeBuildProjectName]
        LambdaArn:
          Fn::GetAtt: [LambdaStack, Outputs.LambdaArn]
        LambdaName:
          Fn::GetAtt: [LambdaStack, Outputs.LambdaName]
        GitHubRepository: !Ref GitHubRepository
        BranchName: !Ref BranchName
