Parameters:
  BucketName:
    Type: String
    Description: The bucket's name which will contain all the project's files.
  AmiId:
    Type: String
    Description: The AMI ID on which the compliance checks will run on (must be a RHEL-based AMI).
  GitHubRepository:
    Type: String
    Description: The name of the GitHub repository hosting the buildspec file.
  ScapGitHubRepository:
    Type: String
    Description: The name of the GitHub repository hosting the SCAP content.
  BranchName:
    Type: String
  
Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: S3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:HeadObject
                Resource:
                  Fn::Sub:
                    - arn:aws:s3:::${Bucket}/*
                    - Bucket: !Ref BucketName
  
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudformation/codebuild.yaml
      Parameters:
        BucketName: !Ref BucketName
        InstanceProfile: !Ref InstanceProfile

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudformation/codepipeline.yaml
      Parameters:
        BucketName: !Ref BucketName
        CodeBuildProjectArn:
          Fn::GetAtt: [CodeBuildStack, Outputs.CodeBuildProjectArn]
        CodeBuildProjectName:
          Fn::GetAtt: [CodeBuildStack, Outputs.CodeBuildProjectName]
        GitHubRepository: !Ref GitHubRepository
        ScapGitHubRepository: !Ref ScapGitHubRepository
        BranchName: !Ref BranchName
        InstanceProfile: !Ref InstanceProfile
        AmiId: !Ref AmiId
