Parameters:
  BucketName:
    Type: String
  AmiId:
    Type: String

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource:
                  Fn::Sub:
                    - arn:aws:s3:::${Bucket}/*
                    - Bucket: !Ref BucketName

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref Role

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: amifactory-rhel8
      LaunchTemplateData:
        IamInstanceProfile:
          Arn:
            Fn::GetAtt: [InstanceProfile, Arn]
        ImageId: !Ref AmiId
        InstanceType: t3.medium
        UserData: |
          IyEvYmluL2Jhc2gNCnl1bSBpbnN0YWxsIC15IGh0dHBzOi8vczMuYW1hem9uYXdzLmNvbS9lYzItZG93bmxvYWRzLXdpbmRvd3MvU1NNQWdlbnQvbGF0ZXN0L2xpbnV4X2FtZDY0L2FtYXpvbi1zc20tYWdlbnQucnBtDQpzeXN0ZW1jdGwgc3RhcnQgYW1hem9uLXNzbS1hZ2VudA==

Outputs:
  RoleArn:
    Value:
      Fn::GetAtt: [Role, Arn]

  InstanceProfileArn:
    Value:
      Fn::GetAtt: [InstanceProfile, Arn]

  LaunchTemplateId:
    Value: !Ref LaunchTemplate
